In [2]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/kropiak/__swps_data_analysis_2026/refs/heads/main/lab_05/data/loan_data.csv') 
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

TASK 1

In [3]:
df = df.rename(columns={'loan_amnt': 'loan_amount'})
print("Columns updated:", df.columns)

Columns updated: Index(['person_age', 'person_gender', 'person_education', 'person_income',
       'person_emp_exp', 'person_home_ownership', 'loan_amount', 'loan_intent',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length',
       'credit_score', 'previous_loan_defaults_on_file', 'loan_status'],
      dtype='object')

TASK 2

In [4]:
task_2a = df[['person_gender', 'person_age', 'person_income']]
print("2a is done.")

task_2b = df.iloc[1000:2001]
print("2b is done.")

task_2c = df.iloc[::2]
print("2c is done.")

task_2d = df[df.index % 2 == 0]
print("2d is done.")

task_2e = df.iloc[:, [0, -1]]
print("2e is done.")

2a is done.
2b is done.
2c is done.
2d is done.
2e is done.

TASK 3

In [5]:
task_3a = df[(df['person_gender'] == 'female') & 
             (df['person_education'].isin(['Master', 'Bachelor'])) & 
             (df['loan_amount'].between(50000, 70000))]

task_3b = df[(df['person_gender'] == 'male') & 
             (df['person_education'] != 'Master') & 
             (df['person_home_ownership'] == 'OWN')]

task_3c = df[df['loan_percent_income'].between(0.4, 0.6)]

task_3d = df[df['loan_amount'] % 10000 == 0]

task_3a.head()

Empty DataFrame
Columns: [person_age, person_gender, person_education, person_income, person_emp_exp, person_home_ownership, loan_amount, loan_intent, loan_int_rate, loan_percent_income, cb_person_cred_hist_length, credit_score, previous_loan_defaults_on_file, loan_status]
Index: []